name: fruits
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dots_indicator: ^3.0.0
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.3
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  intl: ^0.19.0
  lottie: ^3.2.0
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
