name: fruits
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.6.0
  crypto: ^3.0.6
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_localization: ^0.2.3
  flutter_svg: ^2.0.16
  flutter_svg_provider: ^1.0.7
  gap: ^3.0.1
  get_it: ^8.0.3
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  lottie: ^3.2.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.3.3
  sign_in_with_apple: ^6.1.4
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
